version: '3'

volumes:
  pg_data_production:
  static_production:
  media_production:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: kilehook/kittygram_backend
    env_file: .env
    volumes:
      - static_production:/backend_static/
      - media_production:/app/media/cats/images/
    ports:
      - 9000:8000
    depends_on:
    - db
  frontend:
    image: kilehook/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_production:/frontend_static
  gateway:
    image: kilehook/kittygram_gateway
    volumes:
      - static_production:/staticfiles/
      - media_production:/media/cats/images/
    ports:
      - 8081:80
    depends_on:
      - backend